src/components/connect/ndn-testbed.tsx

NDNts retransmits the challenge interest too fast, which doesn't play nice because (presumably?) this generates two separate challegnge requests. After this, the first request is used for sending the challenge response, which doesn't exist anymore (?).
The solution is to prevent the retransmission unless we're quite sure that the interest was lost (after lifetime expires). (note the default is to retransmit at half the interest lifetime)
P.S. I'm not sure; maybe this can be considered a bug in NDNts (or what)
cc @yoursunny

give ndncert more breathing time

---

package.json
patches/pdfjs-dist+3.11.174.patch
patches/pdfjs-dist@3.11.174.patch
pnpm-lock.yaml
src/App.tsx
src/Context.tsx
src/components/common.css
src/components/connect/connect.tsx
src/components/connect/ndn-testbed.tsx
src/components/root-wrapper.tsx
src/components/share-latex/app-tools.tsx
src/components/share-latex/latex-doc/index.tsx
src/components/share-latex/latex-doc/theme.ts
src/components/share-latex/pdf-viewer.tsx
src/components/share-latex/rich-doc/index.tsx
src/components/share-latex/share-latex/component.tsx
src/components/share-latex/share-latex/index.tsx
src/index.tsx
src/testbed.ts
src/workers/sw.ts

WIP
Testing notes: clear vite cache (`node_modules/.vite`) and `pnpm install` again.

UI improvements

---

src/components/connect/ndn-testbed.tsx

Add a loading effect when requesting an email to prevent users from clicking multiple times before the request is completed.

add loading effect when requesting an email

---

src/components/share-latex/file-list.tsx

Added `maxHeight` and `overflowY` settings to the `TableContainer` holding the file list. This should solve #74

File-list scrolling with `maxHeight` and `overflowY` settings

---

src/components/connect/ndn-testbed.tsx

- `ndn-testbed` now imports `ValidityPeriod` from `@ndn/packet` instead of `@ndn/keychain`
- updated a construction of `ClientOptions` to reflect the change
- solved #96

Updated `ValidityPeriod` import

---

build-meta.bash

git describe --tags --abbrev=0 shows the closest tag, resolves #89 .

Showing version in git tag

---

src/components/root-wrapper.tsx
src/index.tsx

- Added `level` to `RouteItem` to represent indentation
- Added `trigger` to `RouteItem` to achieve conditional rendering
- Used `booted` from NDN context as triggers to `Editor` and `Chat`
resolves #84

Implemented multi-level navigation bar for `Editor` and `Chat`

---

src/components/workspace/app-namespace.tsx
src/components/workspace/own-certificate.tsx
src/components/workspace/qr-gen.tsx

- Added QR Code display for workspace trust anchor (`app-namespace.tsx`)
- Added QR Code display for user certificate (`own-certificate.tsx`)
- Used existing `qr-gen.tsx` structure
- changed the errorCorrectionLevel from `L` to `M`
- resolves #87 .

Display Credentials as QR Code

---

build-meta.bash
public/build-meta.json
src/App.tsx
src/build-meta.ts
src/components/workspace/convert-testbed.tsx

This PR updates the homepage and convert page instructions as suggested in #113. Also some minor fixes in `build-meta.sh` for OSX platform (see below)
`date` in OSX doesn't have `%N` and it seems removing it does hurt, so I removed it. Also default bash on OSX is zsh where one needs to escape parenthesis (CMIIW).

update home page instructions and minors

---

src/components/workspace/app-namespace.tsx
src/components/workspace/boot-safebag.tsx
src/components/workspace/own-certificate.tsx

- Adds qr-code display for safebag
- Wraps qr-code displays for certificate and trust anchors so that it's more friendly to users in general
- [Next step] Adds qr-reader for certificate and safebag

Qr-code display for safebag and backdrop around existing ones

---

src/components/workspace/app-namespace.tsx
src/components/workspace/boot-safebag.tsx
src/components/workspace/own-certificate.tsx

This should come with the QR display update, apology.
Now the buttons are only enabled when the inputs are valid (base64, non-empty, parsed successfully, etc.), this should reduce potential confusion and make the page look more consistent

Disable `Show QR Code` buttons when the input is not valid

---

src/components/workspace/app-namespace.tsx
src/components/workspace/boot-safebag.tsx

Currently only trust anchor field implements QR-reader. The video (from camera) is relatively posited and looks awkward especially for mobile users.
This update adds QR reader to safebag field (not containing passphrase) and wrapped existing QR-reader with Backdrop components, so that the video is displayed separately from other components and in full-screen.

Added qr-reader for safebag wrapped with backdrop

---

src/components/workspace/convert-testbed.tsx

As mentioned in #94 , invalid CA cert full name is uncaught and barely notified. This update adds some helper texts and `toast.error` calls to notify the error, as well as re-enabling the "join" button when changes are made to eliminate the need of a refreshing.
Resolves #94

Handling for Convert-Testbed Errors  

---

src/App.tsx

Currently there are no ways to obtain credentials in the form of QR code as mentioned [here](https://github.com/UCLA-IRL/ndn-workspace-solid/pull/117#issuecomment-2244076098).
> Unfortunately adding QR code for safebags on the website does not help. The safebag is obtained **somewhere** and then inputed to workspace for bootstrap. So the most important part is that the **somewhere** should support QR cde display.
This update contains some instructions on converting texts to QR codes in Linux-based environments. Could be a temporary remedy before on-site credential generation is made available

Added instructions to convert text to QR code on linux-based OS's

---

build-meta.bash
src/components/share-latex/app-tools.tsx
src/components/share-latex/path-bread.tsx
src/components/share-latex/share-latex/component.tsx
src/components/share-latex/share-latex/styles.module.scss
src/components/share-latex/simple-pdf/pdf-viewer.tsx

1. f0d465091f33726bf6f1be73a7e2fbc0685e108b Fixed the `./build-meta.bash: 7: [[: not found` error occurring in both `pnpm dev` and `build` processes.
2. 623e35c7fe54208627f3b9fe563417ec9a627ade Resolved an issue where navigating to another view (PDF, both, log) and clicking on a path did not automatically redirect to the editor view, which was unintended behavior.
3. fa7ade7c76086a09e4097384d709e64c2e9f9295 Fixed issues with PDF display and the functionality of the both view. Most modern desktop browsers support using iframes to display PDF files, which is not supported by mobile browsers. However this is still a big improvement over the previous not usable state (Before the pdf view will freeze the whole page except the nav bar and not work on both view). The pdfslick dependency was …

Fix some PDF related issues

---

src/App.tsx
src/backend/main.ts
src/index.tsx

This fixes an annoying bug where you need to go to the home page to connect to testbed. The init is now done in the root component instead, so workspace will connect automatically even if you open, e.g. the `profile` page first.

root: connect to testbed on any page

---

src/components/share-latex/rich-doc/index.tsx

fix: disable dark mode in rich doc

---

src/backend/main.ts
src/components/share-latex/rich-doc/index.tsx

Currently only one attempt is made for prefix registration. If any Interest gets dropped the connection is closed. Unless the command indicates an explicit error, we should retry it.

fix: retry prefix registration

---

src/components/chat/add-channel-dialog.tsx
src/components/chat/chat.tsx
src/components/chat/styles.module.scss

Closes #160 
Closes #159 
Related to #161 (but does not close it because I haven't figured out a way to remove channels yet)
Improvements:
* automatically scrolls to bottom upon entering chat
* enter key sends message (shift+enter for newline)
* prevent sending of empty messages
* messages text now readable instead of white 
* added sent time (hh:mm am/pm) in addition to date
* profile pictures are now 1) deterministic across users/devices, 2) different for each sender, can differentiate people by their PFP
* prettified top navigation bar and buttons
* use memos instead of functions for improved rendering efficiency
* new UI and logic to create a chat channel
* chat channels are no longer hardcoded (other than '#general' to avoid user confusion)
New look:

UI Improvements to Workspace Chat

---

src/backend/main.ts

Untested due to expired local keys at docs/Bootstrap
Will update the keys again when I find time.
This should work, please test.

Snapshot Hotfix: Merge targetSV with localYJS_SV before writing into localYJS_SV

---

src/backend/models/project.ts
src/components/share-latex/share-latex/index.tsx

Currently, the yjs does not distinguish between deleted files and non-deleted files. This means that if a file is deleted and replaced by a new file with the same name, there is no way to tell which is which. This change should allow for workspaces such as the weekly meeting document workspace that only host one file to be more resistant to mistakes (the main file there was already deleted multiple times)
Note: Retry of a previous pull request where I ran into many issues, had to create a new fork to fix.

Added flag for deleted files
